import type {
  SignalBehavior,
  SignalPreset,
} from "@/components/signal/signal-types";

export const PRIMARY_SIGNAL_BEHAVIORS = [
  "presence",
  "attention",
  "listening",
  "reasoning",
  "completion",
] as const satisfies readonly SignalBehavior[];

export const SIGNAL_PRESETS = {
  presence: {
    id: "presence",
    label: "Presence",
    description: "A near-silent trace held together by a slow, quiet breath.",
    transitionMs: 1_100,
    parameters: {
      amplitude: 0.11,
      frequency: 0.2,
      complexity: 0.04,
      velocity: 0.1,
      persistence: 0.91,
      thickness: 0.3,
      noise: 0,
      focus: 0.28,
      depth: 0.08,
    },
  },
  attention: {
    id: "attention",
    label: "Attention",
    description: "Energy contracts toward the center without becoming louder.",
    transitionMs: 560,
    parameters: {
      amplitude: 0.18,
      frequency: 0.29,
      complexity: 0.12,
      velocity: 0.24,
      persistence: 0.88,
      thickness: 0.43,
      noise: 0.005,
      focus: 0.82,
      depth: 0.24,
    },
  },
  listening: {
    id: "listening",
    label: "Listening",
    description: "Harmonics align into a responsive, coherent resonance.",
    transitionMs: 720,
    parameters: {
      amplitude: 0.36,
      frequency: 0.42,
      complexity: 0.24,
      velocity: 0.36,
      persistence: 0.84,
      thickness: 0.48,
      noise: 0.015,
      focus: 0.74,
      depth: 0.36,
    },
  },
  reasoning: {
    id: "reasoning",
    label: "Reasoning",
    description: "Temporary attractors form, fold, and release with intent.",
    transitionMs: 900,
    parameters: {
      amplitude: 0.52,
      frequency: 0.5,
      complexity: 0.78,
      velocity: 0.52,
      persistence: 0.75,
      thickness: 0.56,
      noise: 0.025,
      focus: 0.86,
      depth: 0.88,
    },
  },
  completion: {
    id: "completion",
    label: "Completion",
    description: "The field exhales and resolves gradually into quiet presence.",
    transitionMs: 1_650,
    parameters: {
      amplitude: 0.16,
      frequency: 0.22,
      complexity: 0.06,
      velocity: 0.08,
      persistence: 0.94,
      thickness: 0.34,
      noise: 0,
      focus: 0.42,
      depth: 0.06,
    },
  },
} as const satisfies Record<SignalBehavior, SignalPreset>;
