import type {
  SignalBehavior,
  SignalPreset,
} from "@/components/signal/signal-types";

export const PRIMARY_SIGNAL_BEHAVIORS = [
  "presence",
  "attention",
  "listening",
  "reasoning",
  "completion",
] as const satisfies readonly SignalBehavior[];

export const SIGNAL_PRESETS = {
  presence: {
    id: "presence",
    label: "Presence",
    description: "A near-silent trace held together by a slow, quiet breath.",
    transitionMs: 1_100,
    attractor: {
      type: "none",
      strength: 0,
      stability: 1,
      phase: 0,
      cycle: false,
    },
    oscillator: {
      xFrequency: 1,
      yFrequency: 1,
      frequencyRatio: 1,
      phaseOffset: 0.22,
      xAmplitude: 0.44,
      yAmplitude: 0.24,
      harmonic: 0.045,
      symmetry: 0.86,
      persistence: 0.91,
      energy: 0.22,
    },
    parameters: {
      amplitude: 0.11,
      frequency: 0.2,
      complexity: 0.06,
      velocity: 0.1,
      persistence: 0.91,
      thickness: 0.3,
      noise: 0,
      focus: 0.28,
      depth: 0.08,
    },
  },
  attention: {
    id: "attention",
    label: "Attention",
    description: "Energy contracts toward the center without becoming louder.",
    transitionMs: 560,
    attractor: {
      type: "none",
      strength: 0,
      stability: 0.85,
      phase: 0,
      cycle: false,
    },
    oscillator: {
      xFrequency: 1,
      yFrequency: 1,
      frequencyRatio: 1,
      phaseOffset: 0.29,
      xAmplitude: 0.28,
      yAmplitude: 0.25,
      harmonic: 0.045,
      symmetry: 0.91,
      persistence: 0.88,
      energy: 0.28,
    },
    parameters: {
      amplitude: 0.18,
      frequency: 0.29,
      complexity: 0.12,
      velocity: 0.24,
      persistence: 0.88,
      thickness: 0.4,
      noise: 0.005,
      focus: 0.88,
      depth: 0.2,
    },
  },
  listening: {
    id: "listening",
    label: "Listening",
    description: "Harmonics align into a responsive, coherent resonance.",
    transitionMs: 720,
    attractor: {
      type: "none",
      strength: 0,
      stability: 0.82,
      phase: 0,
      cycle: false,
    },
    oscillator: {
      xFrequency: 1,
      yFrequency: 1.5,
      frequencyRatio: 1,
      phaseOffset: 0.18,
      xAmplitude: 0.58,
      yAmplitude: 0.48,
      harmonic: 0.14,
      symmetry: 0.82,
      persistence: 0.84,
      energy: 0.5,
    },
    parameters: {
      amplitude: 0.36,
      frequency: 0.42,
      complexity: 0.24,
      velocity: 0.36,
      persistence: 0.84,
      thickness: 0.48,
      noise: 0.015,
      focus: 0.74,
      depth: 0.36,
    },
  },
  reasoning: {
    id: "reasoning",
    label: "Reasoning",
    description: "Temporary attractors form, fold, and release with intent.",
    transitionMs: 900,
    attractor: {
      type: "orbital",
      strength: 0.86,
      stability: 0.72,
      phase: 0.08,
      cycle: true,
    },
    oscillator: {
      xFrequency: 2,
      yFrequency: 3,
      frequencyRatio: 1,
      phaseOffset: 0.12,
      xAmplitude: 0.58,
      yAmplitude: 0.58,
      harmonic: 0.24,
      symmetry: 0.68,
      persistence: 0.79,
      energy: 0.66,
    },
    parameters: {
      amplitude: 0.52,
      frequency: 0.5,
      complexity: 0.58,
      velocity: 0.45,
      persistence: 0.79,
      thickness: 0.52,
      noise: 0.015,
      focus: 0.84,
      depth: 0.6,
    },
  },
  responding: {
    id: "responding",
    label: "Responding",
    description: "Cognition opens into a clear, measured outward cadence.",
    transitionMs: 820,
    attractor: {
      type: "fold",
      strength: 0.55,
      stability: 0.88,
      phase: 0.14,
      cycle: false,
    },
    oscillator: {
      xFrequency: 1,
      yFrequency: 2,
      frequencyRatio: 1,
      phaseOffset: 0.1,
      xAmplitude: 0.66,
      yAmplitude: 0.34,
      harmonic: 0.11,
      symmetry: 0.84,
      persistence: 0.83,
      energy: 0.52,
    },
    parameters: {
      amplitude: 0.38,
      frequency: 0.43,
      complexity: 0.26,
      velocity: 0.32,
      persistence: 0.83,
      thickness: 0.48,
      noise: 0.005,
      focus: 0.72,
      depth: 0.36,
    },
  },
  completion: {
    id: "completion",
    label: "Completion",
    description: "The field exhales and resolves gradually into quiet presence.",
    transitionMs: 1_650,
    attractor: {
      type: "figure-eight",
      strength: 0.72,
      stability: 0.97,
      phase: 0,
      cycle: false,
    },
    oscillator: {
      xFrequency: 1,
      yFrequency: 2,
      frequencyRatio: 1,
      phaseOffset: 0,
      xAmplitude: 0.46,
      yAmplitude: 0.36,
      harmonic: 0.02,
      symmetry: 0.98,
      persistence: 0.95,
      energy: 0.34,
    },
    parameters: {
      amplitude: 0.16,
      frequency: 0.22,
      complexity: 0.06,
      velocity: 0.07,
      persistence: 0.95,
      thickness: 0.34,
      noise: 0,
      focus: 0.42,
      depth: 0.06,
    },
  },
} as const satisfies Record<SignalBehavior, SignalPreset>;
