import type {
  SignalBehavior,
  SignalPreset,
} from "@/components/signal/signal-types";

export const PRIMARY_SIGNAL_BEHAVIORS = [
  "presence",
  "attention",
  "listening",
  "reasoning",
  "completion",
] as const satisfies readonly SignalBehavior[];

export const SIGNAL_PRESETS = {
  presence: {
    id: "presence",
    label: "Presence",
    description: "Quiet, persistent energy with a slow and coherent pulse.",
    transitionMs: 980,
    parameters: {
      amplitude: 0.2,
      frequency: 0.24,
      complexity: 0.08,
      velocity: 0.16,
      persistence: 0.9,
      thickness: 0.38,
      noise: 0.02,
      focus: 0.25,
      depth: 0.1,
    },
  },
  attention: {
    id: "attention",
    label: "Attention",
    description: "The trace tightens and gathers energy around its center.",
    transitionMs: 520,
    parameters: {
      amplitude: 0.34,
      frequency: 0.34,
      complexity: 0.2,
      velocity: 0.28,
      persistence: 0.86,
      thickness: 0.46,
      noise: 0.04,
      focus: 0.62,
      depth: 0.18,
    },
  },
  listening: {
    id: "listening",
    label: "Listening",
    description: "Higher responsiveness, texture, and rhythmic activity.",
    transitionMs: 620,
    parameters: {
      amplitude: 0.55,
      frequency: 0.58,
      complexity: 0.48,
      velocity: 0.54,
      persistence: 0.76,
      thickness: 0.58,
      noise: 0.12,
      focus: 0.8,
      depth: 0.3,
    },
  },
  reasoning: {
    id: "reasoning",
    label: "Reasoning",
    description: "Dense harmonic folds produce the most complex behavior.",
    transitionMs: 780,
    parameters: {
      amplitude: 0.72,
      frequency: 0.68,
      complexity: 0.92,
      velocity: 0.66,
      persistence: 0.66,
      thickness: 0.64,
      noise: 0.16,
      focus: 0.92,
      depth: 0.82,
    },
  },
  completion: {
    id: "completion",
    label: "Completion",
    description: "Complexity resolves into a long, deliberate afterglow.",
    transitionMs: 1_280,
    parameters: {
      amplitude: 0.24,
      frequency: 0.28,
      complexity: 0.12,
      velocity: 0.18,
      persistence: 0.92,
      thickness: 0.4,
      noise: 0.01,
      focus: 0.34,
      depth: 0.08,
    },
  },
} as const satisfies Record<SignalBehavior, SignalPreset>;
